# Generated by Django 5.1.5 on 2025-03-18 05:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0003_restaurant_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
